### PR TITLE
Remove School of Haskell

### PR DESCRIPTION
**Pull request by FredericEspiau**
It doesn't exist anymore

### CODE REVIEW

**Comment by krispo** [comment]
Thanks for pointing, It exists here: https://www.schoolofhaskell.com/

**Review by krispo — CHANGES_REQUESTED** [review]
Can you please change the link to: https://www.schoolofhaskell.com/

**Comment by FredericEspiau** [comment]
This is done :)

**Comment by krispo** [comment]
Thanks!

**Pull request merged**
